### ISSUE TITLE
Import highlight labels

### ISSUE THREAD

**Issue by dbobak** [omnivore-app/obsidian-omnivore#35] opened 2023-03-26 15:53 UTC
Is it possible to import not only article labels, but also separate labels for each of the highlight in the article?

**Comment by sywhb** [comment] 2023-03-31 03:44
Hey @dbobak, we have released a new version 1.1.1 to address this issue.

Now you can use the `{{labels}}` variable which has a `{{name}}` attribute, in your template.

I have tagged my highlight with `bug` and `test` labels:
<img width="664" alt="Screenshot 2023-03-31 at 11 29 58 AM" src="https://user-images.githubusercontent.com/12963965/229017271-98eb19a3-c8a8-40d9-9567-c29fd5fcecce.png">

The highlight section in the template:
```
> {{{text}}} [⤴️]({{{highlightUrl}}}) {{#labels}} #{{name}} {{/labels}}
```

**Comment by sywhb** [comment] 2023-03-31 03:45
This is a duplicate of #22

**Comment by dbobak** [comment] 2023-03-31 09:52
Great, thank you!

**Closed** 2023-04-03 11:58 UTC
